name: Deploy Nginx to EC2

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use GitHub's runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo apt update
          sudo apt install -y nginx
          sudo rm -rf /var/www/html/index.html
          echo "Deployed via GitHub Actions" | sudo tee /var/www/html/index.html
          sudo systemctl restart nginx
          EOF

      - name: Verify Deployment
        run: |
          curl -I http://${{ secrets.EC2_HOST }}

